In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt
from sklearn.cross_validation import train_test_split
from sklearn import metrics

/Users/annariehle/anaconda/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
# 1 - Read in Default.csv and convert all data to numeric
data = pd.read_csv('/Users/annariehle/Desktop/Coding Projects/GA Data Science/ds-dc-21/datasets/default.csv')
data.head()

default student      balance       income
0        0      No   729.526495  44361.62507
1        0     Yes   817.180407  12106.13470
2        0      No  1073.549164  31767.13895
3        0      No   529.250605  35704.49394
4        0      No   785.655883  38463.49588

In [3]:
data.describe()

default       balance        income
count  10000.000000  10000.000000  10000.000000
mean       0.033300    835.374886  33516.981876
std        0.179428    483.714985  13336.639563
min        0.000000      0.000000    771.967729
25%        0.000000    481.731105  21340.462905
50%        0.000000    823.636973  34552.644800
75%        0.000000   1166.308387  43807.729275
max        1.000000   2654.322576  73554.233500

In [4]:
data.student = np.where(data.student == 'Yes', 1, 0)

In [8]:
x_train, x_test, y_train, y_test = train_test_split(data[['balance']], data.default, random_state=1)
x_train.shape
y_train.shape
x_train.head()
y_train.head()

651     1
6560    0
8974    0
2348    0
5670    0
Name: default, dtype: int64

In [9]:
# 1 - Run a logistic regression on the balance variable
# 2 - What are the beta values?
logreg = LogisticRegression()
logreg.fit(x_train, y_train)
logreg.coef_
logreg.intercept_

array([-8.57973593])

In [11]:
# 3 - Predict the probability of default for someone with a balance of $1.7k and $2.5k
# your non-default class is in the 0 position while your default class is in the first position 
logreg.predict_proba(1700)

array([[ 0.79081352,  0.20918648]])

In [12]:
logreg.predict_proba(2500)

array([[ 0.11087036,  0.88912964]])

In [13]:
# 4 - Run the below lines to see the sigmoid function with our fitted parameters B0 and B1
# What does beta mean? Let's create some plots to find out!
x = np.linspace(data.balance.min(), data.balance.max(),500)
B0 = logreg.intercept_[0]
B1 = logreg.coef_[0][0]
beta = [B0,B1]

In [14]:
y = np.exp(beta[0] + beta[1]*x) / (1 + np.exp(beta[0] + beta[1]*x))
odds = np.exp(beta[0] + beta[1]*x)
log_odds = beta[0] + beta[1]*x

In [16]:
# 5 - Create predictions using the test set and store them in a variable called ‘preds’
preds = logreg.predict_proba(x_test)[:,1]
print preds

[ 0.00512723  0.01402446  0.00342729 ...,  0.03850793  0.0558485   0.1893638 ]


In [17]:
preds_all = logreg.predict_proba(x_test)
print preds_all

[[ 0.99487277  0.00512723]
 [ 0.98597554  0.01402446]
 [ 0.99657271  0.00342729]
 ..., 
 [ 0.96149207  0.03850793]
 [ 0.9441515   0.0558485 ]
 [ 0.8106362   0.1893638 ]]


In [18]:
# 1 - Compute the accuracy using the accuracy_score from sklearn
predictions = logreg.predict(x_test)
metrics.accuracy_score(y_test, predictions)
# Whoa! That's really high. It's already at 97% not default!

0.9748

In [19]:
# If I guessed 0 everytime, I'd get an accuracy of ~97%
y_test.value_counts() / y_test.shape[0]

0    0.9684
1    0.0316
Name: default, dtype: float64